name: escpos_lib_platform_android_terminals
description: "Yet another ESC/POS Printer Library: Android Terminals"
version: 0.1.0
repository: https://github.com/tfsthiagobr98/escpos_lib_platform_android_terminals
issue_tracker: https://github.com/tfsthiagobr98/escpos_lib_platform_android_terminals/issues

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.dev.tfs.escpos_lib.terminals
        pluginClass: PosSdkPlugin
